### ISSUE TITLE
Lsp server name not getting displayed

### ISSUE THREAD

**Issue by qbnil** [bluz71/nvim-linefly#11]
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/27bf9cd1-1e26-4753-bbee-40ad368d4454)
this only happened recently and the status line stopped showing the active lsp client even tho there is one, for example here: 
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/b2b589cc-04b4-4c9c-934e-a7a09b7290cf)

**Comment by bluz71** [comment]
Hello @qbnil,

The functionality listing attached LSP clients has not changed for a long time. Implied in your issue is that this used to work for you but now does not?

Strange, I can not repeat this on my machines (Linux & macOS).

I installed `lua_ls` through Mason and it works for me for both Neovim `0.10` and `0.9.4`, `lua_ls` is listed in the `statusline` unlike your `-1`.

Are you fully up-to-date, Neovim and all plugins? How is `lua_ls` installed? Mason or something else?

At the moment, I don't know how to debug this without a repeatable test case.

Hopefully you can provide more clues.

**Comment by bluz71** [comment]
I just discovered that Neovim LSP API changed in `0.10` and some functions are removed in `0.11`.

I was using one of the deprecated functions.

I suspect you may be using Neovim nightly. 

Update to the newest version of `linefly`, there is a chance it will fix your issue. Let me know how it goes.

**Comment by bluz71** [comment]
@qbnil,

Are you still experiencing the issue with the latest update?

**Comment by bluz71** [comment]
Closing.
