### ISSUE TITLE
optional mode-indicator

### ISSUE THREAD

**Issue by basilgood** [bluz71/nvim-linefly#12]
Hi, thanks for the plugin, it's simple and offers many customization without writing a ton of code.
Why not an option for mode indicator ?
1. default like it's right now
2. short mode-indicator (n,v,.. or uppercase)
3. no mode indicator

**Comment by bluz71** [comment]
Why? Historic and stylistic choices.

This plugin was spawned from my personal Vim config back in 2013 (or so), before Neovim even existed. I have always had a mode indicator due to personal preference. I like seeing a colorful indicator (as cheesy as that sounds). But I also used the mode indicator to indicate which split was the active split (I don't use `cursorline`), hence I could lose the cursor on the screen, mode-indicator was also the split indicator in my case.

Certain _linefly_ sections are currently always on:

- Mode indicator
- File name
- Position / percentage status

As mentioned in the README:

> _linefly_ has a predominantly fixed layout, this will not be an appropriate statusline plugin if layout flexibility is desired.

Firstly, if `statusline` width is narrow short mode-indicator automatically will become active. Wider mode-indicator has the benefit disambiguating `visual` from `v-line` and `v-rect` modes.

Also, if Neovim global statusline is in effect, `laststatus=3`, and _linefly_ `winbar` is also in effect then the mode indicator, in the `winbar`, doubles as the indicator of which split is active. I find this an important benefit of the mode indicator.

Hence, I prefer to keep the layout as it currently is, mode always visible, not configurable.

Something like the [heirline.nvim](https://github.com/rebelot/heirline.nvim) may suit your needs better? Or `lualine`?

Best regards.

**Comment by basilgood** [comment]
OK! thanks for explanations.
