### ISSUE TITLE
Quickfix issue

### ISSUE THREAD

**Issue by eonpatapon** [bluz71/nvim-linefly#4]
Seems the plugin doesn't handle the special case of quickfix and probably location lists.

With the default status line I can see the quickfix title:

![20230323_17h03m33s_grim](https://user-images.githubusercontent.com/418227/227264452-f35b606b-efd3-4d95-a904-dbd90379afc7.png)

while with linefly there is simply no title:

![20230323_17h04m46s_grim](https://user-images.githubusercontent.com/418227/227264512-9f04e2b1-e390-4c49-b6bc-cdd4ad0f331c.png)

Aside from that, do you think it could be possible to add a setting to disable the mode status ? (normal, visual, etc..)

Thanks for the plugin!

**Comment by bluz71** [comment]
> Seems the plugin doesn't handle the special case of quickfix and probably location lists.

Yes, that is a good suggestion. I have just implemented that in the latest commit; please update and test.

> Aside from that, do you think it could be possible to add a setting to disable the mode status ? (normal, visual, etc..)

Sorry, I don't want to change the overall layout which includes the mode status. This is a simple `statusline` with a mostly fixed layout.

If you like this plugin then you fork it and remove the mode status (from `init.lua`); otherwise something like [Lualine](https://github.com/nvim-lualine/lualine.nvim) will be more configurable.

Best regards,

Dennis.

**Comment by eonpatapon** [comment]
Thanks!
